export const CartData = [
  {
    id: 1,
    name: "Classic Pizza",
    src: "../images/pizza_1.png",
    price: 120,
    quantity: 10,
  },
  {
    id: 2,
    name: "Garlic Burst",
    src: "../images/pizza_2.png",
    price: 120,
    quantity: 10,
  },
  {
    id: 3,
    name: "Stuffed Cheese Pizza",
    src: "../images/pizza_3.png",
    price: 120,
    quantity: 10,
  },
  {
    id: 4,
    name: "Organic Blast",
    src: "../images/pizza_4.png",
    price: 120,
    quantity: 10,
  },
  {
    id: 5,
    name: "Classic Crust",
    src: "../images/pizza_5.png",
    price: 120,
    quantity: 10,
  },
  {
    id: 6,
    name: "Pizza Romania",
    src: "../images/pizza_6.png",
    price: 120,
    quantity: 10,
  },
  {
    id: 7,
    name: "Tomato Pie",
    src: "../images/pizza_7.png",
    price: 120,
    quantity: 10,
  },
  {
    id: 8,
    name: "GrandMa's Fav",
    src: "../images/pizza_8.png",
    price: 120,
    quantity: 10,
  },
  {
    id: 9,
    name: "Royal Mushroom",
    src: "../images/pizza_9.png",
    price: 120,
    quantity: 10,
  },
  {
    id: 10,
    name: "Greek Style",
    src: "../images/pizza_10.png",
    price: 120,
    quantity: 10,
  },
  {
    id: 11,
    name: "Italian Olive Crust",
    src: "../images/pizza_11.png",
    price: 120,
    quantity: 10,
  },
];
